/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FButton {
    }
    interface FText {
    }
}
declare global {
    interface HTMLFButtonElement extends Components.FButton, HTMLStencilElement {
    }
    var HTMLFButtonElement: {
        prototype: HTMLFButtonElement;
        new (): HTMLFButtonElement;
    };
    interface HTMLFTextElement extends Components.FText, HTMLStencilElement {
    }
    var HTMLFTextElement: {
        prototype: HTMLFTextElement;
        new (): HTMLFTextElement;
    };
    interface HTMLElementTagNameMap {
        "f-button": HTMLFButtonElement;
        "f-text": HTMLFTextElement;
    }
}
declare namespace LocalJSX {
    interface FButton {
    }
    interface FText {
    }
    interface IntrinsicElements {
        "f-button": FButton;
        "f-text": FText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "f-button": LocalJSX.FButton & JSXBase.HTMLAttributes<HTMLFButtonElement>;
            "f-text": LocalJSX.FText & JSXBase.HTMLAttributes<HTMLFTextElement>;
        }
    }
}
